### ISSUE TITLE
sharing tests (with xs) works better with modules

### ISSUE THREAD

**Issue by dckc** [Agoric/new-repo#10]
I originally raised this on SwingSet...
https://github.com/Agoric/SwingSet/issues/130

but I suspect it's going to impact other repositories.

So please consider changing this template...

https://github.com/Agoric/new-repo/blob/d321ef896dba4c372e8349de429a78e609b79efb/test/sample-test.js#L4

**Comment by katelynsills** [comment]
You just need the tests within a function `runTests` that is ran like this, right?
```
if (typeof require !== 'undefined' && typeof module !== 'undefined') {
  runTests();
}
```

**Comment by dckc** [comment]
yes, please.

**Comment by dckc** [comment]
Let's use https://github.com/Agoric/agoric-sdk/issues/49 to track this. I might not need the `runTests` function after all.
